apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: guessthename-app
  namespace: default
spec:
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: ./helm # Path to the Charts within the source Repo
      version: "0.2.0"
      sourceRef:
        kind: GitRepository
        name: guessthename
        namespace: default
  values:
    replicaCount: 1
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
