apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: guessthename-app
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ./helm # Path to the Charts within the source Repo
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: guessthename
        namespace: flux-system
  values:
    replicaCount: 1
  install:
    timeout: 10m
    remediation:
      retries: 3
